### ISSUE TITLE
Is there a way to render the file to have a black background with white text? 

### ISSUE THREAD

**Issue by visuelledata** [billthefarmer/diary#106]
Any attempt that I make to edit the css file is falling short. I'm not entirely sure if I'm editing the wrong file. I even tried making a new one.

Is it possible that I'm entering invalid css code into the "Edit styles" menu?

**Comment by billthefarmer** [comment]
I use...
```css
@import url("file:///android_asset/styles.css");

body {
background: darkslategray;
color: white;
}

a {
color: white;
}
```
If you want black, put `black` instead of `darkslategray`. To revert to default change it to...
```css
@import url("file:///android_asset/styles.css");

#body {
background: darkslategray;
color: white;
}

#a {
color: white;
}
```
**Note** the `#` is not a comment, it is changing the tag so it doesn't match anything. Alternatively you can use...
```css
@import url("file:///android_asset/styles.css");

body {
background: cornsilk;
}
```
